development:
  adapter: postgresql
  encoding: unicode
  database: app_postgresql_development
  pool: 5
  username: postgres
  password: abcd1234

test:
  adapter: postgresql
  encoding: unicode
  database: app_postgresql_test
  pool: 5
  username: postgres
  password: abcd1234
